CC = gcc
CFLAGS = -Wall

ex2:
	$(CC) $(CFLAGS) -o paginas ex2_1617.c

ex3:
	$(CC) $(CFLAGS) -o ex3 ex3_1617.c

ex4:
	$(CC) $(CFLAGS) -o controlador ex4_1617.c

ex5:
	$(CC) $(CFLAGS) -o streamer ex5_1617.c