CC = gcc
CFLAGS = -Wall

ex1:
	$(CC) $(CFLAGS) -o ex1 ex1.c

ex2:
	$(CC) $(CFLAGS) -o ex2 ex2.c
	$(CC) $(CFLAGS) -o p1 p1.c
	$(CC) $(CFLAGS) -o p2 p2.c
	$(CC) $(CFLAGS) -o p3 p3.c

ex3:
	$(CC) $(CFLAGS) -o ex3 ex3.c