CC = gcc
CFLAGS = -Wall

ex1:
	$(CC) $(CFLAGS) -o 10mb ex1.c

ex2:
	$(CC) $(CFLAGS) -o mycat-v1 ex2.c

ex3:
	$(CC) $(CFLAGS) -o mycat-v2 ex3.c

ex5:
	$(CC) $(CFLAGS) -o mycat-v3 ex5.c

ex6:
	$(CC) $(CFLAGS) -o nl-v1 ex6.c

ex7:
	$(CC) $(CFLAGS) -o pessoas ex7.c ../guiao0/person.o